I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script call
    call eventCheck
  File "game/script.rpy", line 40, in script
    if Hours == 12:
  File "game/script.rpy", line 40, in <module>
    if Hours == 12:
NameError: name 'Hours' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script call
    call eventCheck
  File "game/script.rpy", line 40, in script
    if Hours == 12:
  File "/Applications/renpy-8.0.3-sdk/renpy/ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "/Applications/renpy-8.0.3-sdk/renpy/python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-8.0.3-sdk/renpy/python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 40, in <module>
    if Hours == 12:
NameError: name 'Hours' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
Month Week Clock 1.0
Wed Feb  1 16:06:32 2023
